### ISSUE TITLE
Manubot vs. alternatives

### ISSUE THREAD

**Issue by mostafachatillon** [manubot/rootstock#109]
I just found out about Manubot, can you tell the differences between Manubot and alternatives, like:

- Authorea
- Gitlab
- Overleaf
- Google docs...

**Comment by dhimmel** [comment]
Hey @mostafachatillon, thanks for your question. We'd love for you to try out Manubot should it be appropriate for your needs.

Some general differences between Manubot and the services you mention:

+ Manubot uses git for version control and can use the full set of git collaboration tools, such as GitHub PRs. Some other services do use git to store manuscripts, but I don't believe they offer collaborative features based on git, such as pull requests. As a result, I think Manubot is best for an open contributions model, where anyone can propose an update to the manuscript. However, project maintainers have to approve all contributions.

+ Manubot is customizable. Since Manubot is open source and allows each instance (mansucript) to change its behavior. Other services will provide only limited customizability.

+ Version history is public is Manubot.

+ Manubot is Pandoc markdown based.

+ Manubot has advanced scholarly writing features, like citation by ID and CSL citation style support.

+ Manubot is more for technical users. If you are comfortable with git and like continuous integration, you will like Manubot. It's a good tool for those who have used LaTeX in the past, but would like a more modern scholarly writing experience.

There are some other issues discussing specific services:

+ Overleaf https://github.com/greenelab/meta-review/issues/27
+ Gitlab https://github.com/greenelab/manubot-rootstock/issues/88

If it helps you decide, I created Manubot after tying to use Authorea for my [PhD thesis](https://doi.org/10.6084/m9.figshare.4724797). Also note that via Pandoc, you can export Manubot manuscripts to many other formats.

**Comment by dhimmel** [comment]
Perhaps the intro from [this document](https://greenelab.github.io/manufund-2018/) (created with manubot) will be informative:

> Manubot is a system for writing scholarly documents on GitHub. Manubot aims to **transform publishing** to be transparent & reproducible, immediate & permissionless, versioned & automated, collaborative & open, linked & provenanced, decentralized & hackable, interactive & annotated, and free of charge.
> 
> Manubot transfers the lessons from the **open source software movement** to academic writing. Documents are written in the open, creating an easy path for readers to become contributors. We recommend following a workflow where anyone can propose changes, which are then reviewed by project members and revised as necessary before being incorporated (for example, [see how](https://github.com/greenelab/manufund-2018/pull/2) this proposal was created).
> 
> Manubot is based on a collection of open source **tools and standards**. Manuscripts are written in markdown, using git for version control and GitHub for collaboration and review. Users can cite standard persistent identifiers and Manubot retrieves bibliographic details to automatically create a reference list. Conversion between formats (e.g. from markdown to HTML, PDF, and DOCX) is done using [Pandoc](http://pandoc.org/). When the manuscript changes, continuous integration automatically rebuilds and deploys it `[@doi:10.1038/nbt.3780; @doi:10.1038/550143a]`.

I kept the citations pre-formatted, so you can see how you do citations with Manubot.

**Comment by mostafachatillon** [comment]
I would appreciate a point-by-point comparison between Manubot and Authorea.

I am new to collaborative writing, I started a paper a couple of days ago on Authorea:
https://www.authorea.com/users/226673/articles/285209-diversitynet-a-collaborative-benchmark-for-generative-ai-models-in-chemistry

Customer service/Community :
. Authorea: no or slow responsiveness, I am not sure if this project is still very active. I am worried. 

Manubot: quick answers. Moreover, it helps to know that Manubot is made by authors of the deep learning for medicine paper. That’s exactly my topic.

User interface/ease of use:
Authorea: very nice, they are catching up with Medium. 

Manubot: confusing, I am still trying to figure out how it works. My project wants to regroup data scientists, who are supposed to know Latex, Github and Python, with chemists, who only know Microsoft Word. I don't know if Manubot is good for that.

Marketing/visibility : 
Authorea: good presence on social networks 

Manubot: I didn’t know it existed, despite that I was closely following the deep learning for medicine paper. I made an extensive search for collaborative tools, and Manubot did not appear on Google. It would help doing a landing page, at least. 
The name 'Manubot' is not informative about the product. It sounds like a chatbot, not a collaborative writing tool.

Cost:
Authorea: it’s not free to get a DOI and to post on Biorxiv or Arxiv.  I don't know how to get a PDF or a Latex file of the paper, it's strange.

Manubot: 100% free, and open-source.

Conclusion: 
I think Manubot is more promising in the long term, but at the moment, Authorea remains one step ahead in terms of ease of use.

For my paper, I prefer to stay on Authorea at the moment, but I am open about migrating to Manubot, especially if there are Manubot fans among my co-authors. I will mention Manubot in my blog to inform people about this alternative.

**Comment by dhimmel** [comment]
Thanks @mostafachatillon for your comparison. It's helpful to know what aspects authors care about.

Based on your comments, I'd stick with Authorea until you encounter a feature that Authorea cannot provide. Then you could re-evaluate whether Manubot could suit your needs better. If so, I'd be happy to help you set it up and migrate from Authorea.

> Authorea: no or slow responsiveness, I am not sure if this project is still very active. I am worried.

The project is active, but as an open source project, we make no guarantees. However, you don't have any dependency on Manubot maintainers once you set up a manuscript. Unlike with Authorea, you don't rely on us to host your manuscript (with the current Manubot setup you do rely on GitHub and Travis CI).

**Comment by agitter** [comment]
@mostafachatillon thanks for your feedback.  I haven't used Authorea, but I have used Overleaf for a few recent papers.  I'm assuming the features are somewhat similar.

Overleaf has worked great for me when writing with 1-2 other people.  For an ongoing paper with 6 active authors, it has been confusing.  Even though we can version the document and track changes through its git commits, it is hard to assess what parts of the manuscript have changed recently and who made the changes.  The git commits seem to integrate changes from multiple authors under certain circumstances, which would impair contribution-tracking on a many-author project.  However, even non-LaTeX users have been able to edit text and ignore the equations and LaTeX-specific syntax or work in WYSIWYG mode.

My favorite Manubot feature is the integration with pull request review and issue tracking.  This was essential for the Deep Review, and I wish I had it for some other multi-author projects.  It slows down the workflow (because changes have to be discussed and approved), but I think it is important for scaling to a large number of authors.  Google Docs at least has suggestion mode, where proposed changes must be explicitly accepted, but there isn't support for review.

If you are working with chemists, then editing the Markdown files through the GitHub site directly may be the simplest option for using Manubot.  The Markdown changes can be previewed, and they could avoid using git locally.  They could still run into merge conflicts, but a project maintainer (e.g. you) could help resolve those.

As @dhimmel said, you may be fine staying on Authorea until you run into problems.

**Comment by agitter** [comment]
The Manubot manuscript has a section on [collaborative writing platforms](https://greenelab.github.io/meta-review/#collaborative-writing-platforms) that will be a good resource for anyone else who has similar questions.
