### ISSUE TITLE
Show context for references

### ISSUE THREAD

**Issue by agitter** [manubot/rootstock#118]
Building on @dhimmel's post [on author versus numeric citation styles](http://blog.dhimmel.com/citation-styles/), another advantage of author-based citations in the current version of Manubot is that it is easier to find where a reference is cited.  I can search for `Pantcheva, 2018` more easily than `13`, for instance, especially if `13` is cited as `12-14` or appears in numeric parts of the text.

A nice feature for numeric citations might a form of "show context" that some journals use.  https://www.nature.com/articles/ncomms12989#references is an arbitrary example.  The context consists of snippets of the manuscript where the reference was used plus links back to those locations.

This would also give us one way to address #117.  We could assert that the reference number is an increasing function of the reference's first context.

**Comment by dhimmel** [comment]
The problem with searching 13 is two-fold. First, you'll get false positives when searching (for example, all references with the year 2013). Second, 13 isn't printing since its inside the range of cited numbers. For this second issue, I'd like to turn off using dashes for sequential range of numbers. Dashes make sense for print media only, where the modicum of space saving is worth it because there are no downsides. However, the downside of dashed numeric citation sequences in digital media is higher:

+ the citation number is missing making it hard to search for the citation
+ the citation is missing, and hence not linked, making computational analysis harder
+ we want citations to have tooltips with the reference, so there is no need to consult the bibliography. However, dashes make it so you can only access the first and last citations.

Therefore, I think the first course of action should be to try to disable dashed ranges of citations in the default Manubot citation style.

Regarding the reference-to-citation lookup, eLife Lens has a nice interface for this ([example](https://lens.elifesciences.org/26726)). Each reference has a "Focus" button which highlights the location of the citations. Also you also can click a citation to highlight all other citations to the same references. Therefore, are we able to export to JATS (see https://github.com/greenelab/manubot-rootstock/pull/82) and integrate Lens, we can piggy-pack on this already implemented solution.

It looks like pandoc doesn't have a way to link references back to individual citations ([as per this discussion](https://groups.google.com/forum/#!topic/pandoc-discuss/pj7E0t3YPXw)), like you would see on wikipedia.

**Comment by agitter** [comment]
Disabling dashed ranges of citations would be an improvement.  It eliminates false negatives.  False positives are tolerable because one can search `13]` and `13,`.

I also like tooltips but haven't considered the technical requirements.

**Comment by agitter** [comment]
Manubot now supports this functionality
