### ISSUE TITLE
Plugin suite test - round 1

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#185]
@cgreene @dhimmel @agitter @slochower @vsmalladi 

https://www.vincentrubinetti.com/manubot/

I've created a test bed for the Manubot front-end (`.html` export/output) plugins, available at the above temporary link. You can turn plugins on/off and set their options, then click `Go` to go to a test/template manuscript that allows you to play around with the plugins' features. Hover over an option to see a description of it.

Please test this page on all devices and browsers you can, with as many permutations of plugins and options as you can. Try to break things and cause unexpected behavior. Please report any bugs you find and make suggestions in a reply to this issue.

Note that there are some browsers we wont be supporting, and there are more features that we're planning to add in the future. But for the sake of completeness, comment on everything you can think of here.

You might want to make your own manuscript to test things with; maybe one with more text, links, and different kinds/shapes/sizes of images. If you'd like to do this, and you are unfamiliar with Manubot, and you're in the Greene Lab, come see me and I can help you set it up.

**Comment by agitter** [comment]
I did some light testing with default manuscript settings in Edge 42.17134.1.0 on Windows 10.

What are the separator characters or images in between the author attributes?
![image](https://user-images.githubusercontent.com/3532898/53829105-03c44b00-3f45-11e9-9ba0-9b21cbd90f9a.png)

Everything else worked perfectly.  It is actually a little jarring at first to have such a dynamic manuscript.  I'm not used to being able to jump around to different instances of references, for instance.  I also had to stop and think about how to return to a figure after I had clicked the link to where it is first referenced in the manuscript.  My instinct was to click back instead of clicking the Figure N link.

However, I like the new features very much and think they will be very useful after a short adjustment period.  The ability to preview references is something I've been looking forward to for a long time.

**Comment by vincerubinetti** [comment]
> I did some light testing with default manuscript settings in Edge 42.17134.1.0 on Windows 10.
> 
> What are the separator characters or images in between the author attributes?
> ![image](https://user-images.githubusercontent.com/3532898/53829105-03c44b00-3f45-11e9-9ba0-9b21cbd90f9a.png)

Sorry, I forgot to upload the twitter etc. icons to the website. Did that now, it should work. What you're seeing there is your brower's default "broken image" icon, cut off.

> Everything else worked perfectly. It is actually a little jarring at first to have such a dynamic manuscript. I'm not used to being able to jump around to different instances of references, for instance. I also had to stop and think about how to return to a figure after I had clicked the link to where it is first referenced in the manuscript. My instinct was to click back instead of clicking the Figure N link.
> 
> However, I like the new features very much and think they will be very useful after a short adjustment period. The ability to preview references is something I've been looking forward to for a long time.

I might actually be able to add this feature in by putting a hash in the url (eg `#fig:square-image`) when clicking one of the "jump to" buttons. Whenever you change the hash in the url, you can navigate forward/backward as if it were a normal history entry.

**Comment by dhimmel** [comment]
In Chrome 72.0.3626.121 on Android 9 on Pixel 2, clicking a citation navigates to the reference in the bibliography rather than showing the tooltip. Talking with @vincerubinetti, he believed this had to do with how my browser handles hover elements. One option could be to always raise the tooltip on the first touch click and then navigate to references on a touch click of an already activated citation tooltip.

On desktop, I noticed tooltips were frequently getting activated while I moved my cursor across large swaths of page. Would it make sense to require a certain duration of hover or lack of cursor velocity to activate tooltips?

**Comment by agitter** [comment]
> Did that now, it should work.

Yes, that looks better now.

> I might actually be able to add this feature in by putting a hash in the url (eg #fig:square-image)

Let's wait for a little more feedback before testing this change.  It may not be a real problem.

> Would it make sense to require a certain duration of hover or lack of cursor velocity to activate tooltips?

I like the idea of adding a small delay or similar test to make sure the tooltips aren't too aggressive.

**Comment by ypar** [comment]
A quick look. I can check other things and devices if need be.
Firefox 65.0.1 on a Pixel XL and Chrom 72.0.3626.109 on a MacBook Pro.

* loading
In general, with my slow internet, neither device was loading the test bed quickly. For 'Link with hover text', for example, the text took more than three seconds to show up. Likely not an issue with other users.

* tooltips
To me, the plugin option names were not intuitive. Tooltips were useful because otherwise I wouldn't quite understand what all these options were. However, I thought it looked very much like the 'our website use your cookies...' message with its tone and placement. Maybe lighter color background or simpler statements would help. 

* menu icons
When the browser is narrow (< 5 inches on a laptop or the vertical view on mobile), menu icons on top of both pages are within the text space. It did not bother me on a laptop browser. It bothered me a bit on mobile because I was quickly scanning through multiple lines at ones and it's proportionately more space on a phone than on a laptop. Likely a non-issue if someone were to actually read a scientific article (slowly, one line at a time). This problem solves itself for larger laptop browser widths and the horizontal view on mobile. I also couldn't tell what the icons on the top right are supposed to do. What is en eye doing here? It seemed a bit creepy at first glance. Maybe a highlighted box to indicate a highlight function?

* figure default views when clicked
Too small on a laptop browser. Too big on a vertical mobile. Figure 4, for example, showed only the middle 30% or so when I clicked it on a vertical phone. It was about a third of its within-text size when I clicked it on my laptop. Figure 3 only shows the bottom half when I click it on a vertical phone. The mobile horizontal view worked well with defaults. All zoom in and out adjustments work fine on both devices.

* equation (2) 
It shows up fine on mobile. It breaks down and doesn't fully show up when I narrow the browser to less than half-width of a laptop. 

* long table scroll
It doesn't work on my phone. 

* unicode superscripts and unicode subscripts
They look great on mobile. They are broken with empty boxes and varying font sizes on my laptop.

**Comment by cgreene** [comment]
When I mouseover the references within the manuscript for Figure 4, and then mouse to another item below it, Figure 4 stays displayed. In this one, I was moused over Figure 1.

![screen shot 2019-03-06 at 8 59 19 am](https://user-images.githubusercontent.com/542643/53886507-2bbbb900-3fee-11e9-93e4-63a263d70626.png)

**Comment by vincerubinetti** [comment]
> When I mouseover the references within the manuscript for Figure 4, and then mouse to another item below it, Figure 4 stays displayed. In this one, I was moused over Figure 1.
> 
> ![screen shot 2019-03-06 at 8 59 19 am](https://user-images.githubusercontent.com/542643/53886507-2bbbb900-3fee-11e9-93e4-63a263d70626.png)

That "Figure 1" below "Table 1" is actually supposed to say "Equation 1", I made a typo. And we're not doing equations in tooltips (at least not yet), so it still stays on the last figure you hovered. I fixed the typo.

**Comment by dhimmel** [comment]
> unicode superscripts and unicode subscripts
They look great on mobile. They are broken with empty boxes and varying font sizes on my laptop.

@vincerubinetti since we're loading fonts, why would this happen?

**Comment by vincerubinetti** [comment]
> > unicode superscripts and unicode subscripts
> > They look great on mobile. They are broken with empty boxes and varying font sizes on my laptop.
> 
> @vincerubinetti since we're loading fonts, why would this happen?

Unicode defines tens of thousands of characters, and not all fonts support all of them. Most fonts support only a small subset. I chose the most popular Google sans-serif font hoping that it would have the most character support, but it still might not have all of them.

Further, it's possible with slow internet that the Google Font doesn't load and it falls back to some system default sans-serif font that doesn't have the unicode characters. Either way, this is kind of out of our control.

**Comment by vincerubinetti** [comment]
>   In general, with my slow internet, neither device was loading the test bed quickly.

Can you elaborate? Was the manuscript loading slow, or just the plugin options page? If it was the manuscript, can you describe how the page loaded (eg, "the text showed up instantly but images took a while to load and it took some time for the table of contents and accordion arrow buttons to show up")

>   To me, the plugin option names were not intuitive.

I'm open to suggestions for better option names. They have to be short though because those are variables in the code.

> I thought it looked very much like the 'our website use your cookies

The options page is not actually going to be part of manubot, released to the public. That was just a quick page I made to be able to quickly test different combinations of the plugins/options. That said, the option names mirror the actual variable names in the code, and the tooltip text mirror the comments right above the options in the code.

> * menu icons
>   menu icons on top of both pages are within the text space. 

That is by design. I tried squeezing the text inward to make room for the icons, but it looks bad having a bunch of empty white space on the sides, and is also not ideal for super small screens like the iphone 5s (only 320px wide) because it multiplies the vertical length of the document by a lot.

>  I also couldn't tell what the icons on the top right are supposed to do. What is en eye doing here?

This is a third party plugin called [hypothesis](https://web.hypothes.is/). Not being from academia myself, I don't know how widely known it is, but supposedly it's the standard for making online/sharable comments/annotations on web pages.

> figure default views when clicked
> Too small on a laptop browser.

By design, default zoom will be 100% (actual size) and scale down to fit the viewport if necessary. Imo, images should default to actual/specified size if possible, to make sure images containing pixel perfect imagery are preserved properly.

> Figure 4, for example, showed only the middle 30% 

On a big enough screen, the images should popup at the same size as they are in the document. I'm looking into this. Probably has to do with the fact that Fig 4 is an SVG.

> Figure 3 only shows the bottom half when I click it on a vertical phone

Can you post a screenshot. Which browser/OS was this.

> It breaks down and doesn't fully show up when I narrow the browser to less than half-width of a laptop.

Can you elaborate? You should be able to scroll the equation box left/right.

> * long table scroll
>   It doesn't work on my phone.

Can you elaborate? Does the table just overflow past the edge of the document? Does it just squash the table? Is there a scrollbar? Can you post a screenshot?

> * unicode superscripts and unicode subscripts

Replied to this in above comment.
