### ISSUE TITLE
Add link to meta-review in README of rootstock

### ISSUE THREAD

**Issue by slochower** [manubot/rootstock#216]
I think we should add a citation to the meta-review here. If I redirect someone to www.manubot.org (which comes to this repository), there isn't a quick & easy thing describing the advantages and disadvantages, which we have laid out in meta-review. What do you think @agitter?

**Comment by agitter** [comment]
The list time we discussed this in https://github.com/manubot/manubot/issues/59 we decided to put the meta review link in USAGE.md to help avoid confusion about what to cite in manuscript repositories.  However, that may have been before www.manubot.org, and the meta review itself has changed substantially since then.  It is now a much better explanation of why someone should use Manubot.

I'm open to making the meta review link more prominent in the main readme.  Unless there are plans to build out www.manubot.org in the short term and make that the best resource for prospective users.

**Comment by slochower** [comment]
Right. I think putting it more prominent is good. Someone is only going to click on `USAGE.md` if they want to use the package... which they might not want to do unless they see some justification and cool features :)

**Comment by dhimmel** [comment]
I think https://github.com/manubot/rootstock/pull/217 is a good start. Hopefully, we'll get a landing page up in the next couple months, that provides a better overview than the rootstock repo.

**Comment by slochower** [comment]
Agree, sounds good for now.
