### ISSUE TITLE
Local-path figures not rendered in output/manuscript.html

### ISSUE THREAD

**Issue by sbonaretti** [manubot/rootstock#237]
Hi,
I am learning manubot and the learning curve is very fast! I really like it! Thanks for creating it!  
Two quick questions:  
- My figures are not rendered in .html, but they are rendered in .pdf. Do you have any suggestions on what I should double-check?  
- When I run `build.sh` I get a bunch of warnings (see attachment). Do you have any recommendations on how to fix them?
Thanks a lot!
Serena 

<img width="859" alt="warnings" src="https://user-images.githubusercontent.com/13563701/60182035-c7826680-9823-11e9-8317-a3c7b188087a.png">

**Comment by dhimmel** [comment]
Sounds like you are most interested in the local builds (as opposed to builds through Travis CI). That is OKAY, just that this is the most complex workflow. But thanks for trying it out and reporting issues!

> My figures are not rendered in .html, but they are rendered in .pdf. Do you have any suggestions on what I should double-check?

Interesting. Are you opening `output/manuscript.html` and not seeing the images? That is actually expected if your images are provided by local path (rather than by URL to an external repo or location). If after you run your `sh build/build.sh`, you run the following:

```sh
# Configure the webpage directory
python build/webpage.py
```

Then you should be able to open `webpage/index.html` and see the images. Let me know if this addresses the issue? We'll think about how the documentation can make this more clear.

> I get a bunch of warnings (see attachment). Do you have any recommendations on how to fix them?

I think all those warnings are from the HTML to PDF conversion by WeasyPrint. They can be safely ignored. Note that on Travis CI and local systems with Docker installed, we use a different program called athenapdf to convert from HTML to PDF. athenapdf doesn't output all these warnings.

**Comment by sbonaretti** [comment]
Yes, I am using the local build - it feels a lot like sphinx, and thus it feels familiar to me.
The python command works, and the images get rendered in `webpage/index.html`. 
I will be happy to ignore the warnings.
Thanks for replying and helping me out so quickly!

**Comment by dhimmel** [comment]
> I will be happy to ignore the warnings.

Cool, you can also do `BUILD_PDF=false bash build.sh` to suppress building PDF altogether if you only care about the HTML output.

We can leave this issue open until we either update the docs or redesign the layout such that images in `output/manuscript.html` work.

**Comment by sbonaretti** [comment]
Great! Thanks!

**Comment by agitter** [comment]
We could also consider adding some of these common WeasyPrint warnings to [`build/README.md`](https://github.com/manubot/rootstock/blob/master/build/README.md) so that new users know it is okay to ignore them.
