### ISSUE TITLE
Rename themes back to .css from .html

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#241]
Even though the theme files are technically `.html` (well, they're really fragments of a valid `.html` file), I think we should rename them back to `.css`. For those who know what CSS is, they might be looking around for where to modify the CSS, and would be confused to find it in an HTML file, probably.

**Comment by dhimmel** [comment]
Hmm but these are not valid .css files due to being wrapped in `<style>`:

https://github.com/manubot/rootstock/blob/ed4158c9f2a1b300f82d058be9aefe1f5eb72763/build/themes/default.html#L1-L4

Therefore I think just changing the extension would mess up syntax highlighting, linting, and the semantics of inserting this file directly into an HTML document.


but this will mess up syntax highlighting. With the wrapping  they are not valid CSS files.

Would using a name like `default-css.html` or `default-style.html` help with the confusion?

Also are we sure that we'll never need to put other HTML content other than style in the default theme?

**Comment by vincerubinetti** [comment]
> would mess up syntax highlighting, linting

I think these things can be configured such that the file is just treated like an HTML file. Some linters may even be smart enough to just recognize that it's html.

But also, if we're talking about semantics, this file really truly is a CSS file. I don't think we'll ever need to add anything else but CSS to it.

Maybe we can get rid of the surrounding `<style>` tags, and import it into the `html` export through the pandoc template, similar to how mathjax is currently being included.

**Comment by agitter** [comment]
Removing the `<style>` tags and making this a `.css` file or renaming the existing file `default-css.html` both seem like reasonable solutions.  I added a reference to this file in #245, which may partly help as well.
