### ISSUE TITLE
Store thumbnail in the repo itself

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#267]
I think it's pretty certain that we eventually want to have people put their thumbnails in their papers' repositories. We had discussed whether or not to do this, but after thinking about it more, I think we definitely should. If it's in the repository, the thumbnail can also be used as a [share thumbnail](https://manubot.org/share-thumbnail.png) (the image you see when you share a link on facebook, twitter, etc), and possibly even a favicon.

This is also why I'm changing the terminology to be consistently "thumbnail" instead of "screenshot" (which is less descriptive and less accurate).

I think we should simply specify that the thumbnail has to be named `thumbnail.png`, and be either in the root of the repo, or in `/content` (what do you guys think). And we can include the [default thumbnail](https://manubot.org/catalog/thumbnail.png) in rootstock that will automatically instruct people (at least partially) what format and size they should be. And we can link to the thumbnail guidelines in the catalog repo for more instructions.

**Comment by dhimmel** [comment]
Perhaps the essence of this issue is that we should have a way to allow the user to set the thumbnail. I can imagine two possible routes to setting the thumbnail:

1. by including an image file in the repository. `content/images/thumbnail.png` would probably be the most consistent with our current repo organization. If Manubot detects this file, it would automatically use it as a thumbnail.
2. by manually specifying the location of a thumbnail image by URL. For example, `metadata.yaml` could support a `thumbnail_url`. This would be useful for users who have their thumbnail stored or managed at another location.

In https://github.com/manubot/rootstock/issues/176, we discuss setting some HTML header fields with metadata. It seems like their are also metadata fields for thumbnails? I wonder if the best route for manuscript consumers (like the Manubot catalog, see https://github.com/manubot/catalog/issues/10) to extract the thumbnail would be from the HTML metadata? This way consumers would not have to navigate all the possible ways a thumbnail could be specified in the source repository.

It seems we have been assuming the thumbnail will always be a PNG? What if the user has access to the underlying vectors, should SVG not be supported? Likewise, if the thumbnail is an actual image, would JPG support make sense? I guess what conditions do browsers impose on thumbnails and what conditions do we want to impose for interoperability (refs https://github.com/manubot/catalog/pull/9/files)?

**Comment by vincerubinetti** [comment]
Favicons come in a few different types:

`.ico` - deprecated, in the sense that all modern browsers (maybe not IE) support the option below
`.png` - all modern browsers support this, and it seems that it can be any resolution (but 192x192 seems safe). unfortunately, chrome (and possibly others) seem to prefer the 16x16 `.ico` if it is present before using the higher resolution `.png`
`.svg` - unfortunately, browsers stupidly don't support this yet. the only place i know of where an svg is used as a favicon is in the macbook touch bar

The share-thumbnail should also typically be in png. So as you can see, I tried to choose the thumbnail format and size in such a way that would work for everything. Worst case is we might have to scale it down.

**Comment by dhimmel** [comment]
> Favicons come in a few different types:

I thought that favicons were intended to be separate from the thumbnail: see https://github.com/manubot/rootstock/issues/181. Are you thinking that the thumbnail could be used as the favicon? My preference would be to default the favicon to the manubot logo and allow users to change it to a custom favicon, but probably not a 1000x1000 thumbnail?

**Comment by vincerubinetti** [comment]
> Are you thinking that the thumbnail could be used as the favicon? 

Yes, see the original post of this issue.

If they're following the thumbnail guidelines I laid out, their thumbnail should look OK at small resolutions. I kind of doubt anyone will go to the trouble of making a different thumbnail and favicon, but they'll definitely go through the trouble to make a thumbnail.

And then if the thumbnail isn't specified, it'll use the manubot logo as a placeholder.

**Comment by dhimmel** [comment]
> And then if the thumbnail isn't specified, it'll use the manubot logo as a placeholder.

Sounds good to me, assuming 1000x1000 thumbnails seem to render okay as favicons. If not, we could always just use the manubot logo for all favicons and not support favicon customization for the time being.

Here's the architecture sketch I made regarding how thumbnails can get set and detected. More comments on the design at https://github.com/manubot/catalog/issues/10#issuecomment-529661064:

> ![IMG_20190909_172648 (1)](https://user-images.githubusercontent.com/1117703/64567895-554ff700-d327-11e9-87ed-bf46f9779130.jpg)

Here are the metadata attributes set for https://het.io/ by this [source](https://github.com/hetio/het.io/blob/e2d4550a3fffbf12bd61cfdd22f2ed3db3356860/_layouts/default.html#L14-L33)


```html
    <meta property="og:image" content="/share-thumbnail.png" />
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content="https://het.io" />
    <meta property="twitter:title" content="Het.io - {{ page.title }}" />
    <meta property="twitter:description" content="{{ page.description }}" />
    <meta property="twitter:image" content="/share-thumbnail.png" />

    <!-- favicons - https://realfavicongenerator.net/ -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link
      rel="icon"
      type="image/png"
      sizes="192x192"
      href="/favicon-192x192.png"
    />
    <link rel="manifest" href="/site.webmanifest" />
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#02b3e4" />
    <meta name="msapplication-TileColor" content="#02b3e4" />
    <meta name="theme-color" content="#02b3e4" />
```

For things like the manubot logo favicon, it seems like it may simplify things if we can load it from an external manubot URL, which [works according](https://stackoverflow.com/a/6387488/4651668) to this unofficial source. It also seems that we [don't need](https://bitsofco.de/all-about-favicons-and-touch-icons/) favicons and thumbnails in the root webpage directory (although doing so enables them to be automatically detected even if not specified in the HTML).

**Comment by vincerubinetti** [comment]
>  It also seems that we [don't need](https://bitsofco.de/all-about-favicons-and-touch-icons/) favicons and thumbnails in the root webpage directory

I've seen a couple of sources say that it's not recommended, namely that realfavicongenerator.net site. But it's true that probably most modern browsers will be okay with it. I'll defer to you.

**Comment by dhimmel** [comment]
I'm brainstorming how the manubot python package should work with roostock to detect/set thumbnails.

Currently, I'm thinking we could accept two optional fields in `metadata.yaml` for `thumbnail_path` and `thumbnail_url`. `thumbnail_path` refers to a local path in the repository (i.e. `thumbnail.png` or `content/images/thumbnail.png` or `assets/thumbnail-new.png`, etc). `thumbnail_url` refers to a URL pointing to a thumbnail. This allows thumbnails to be stored elsewhere than the git repo.

If neither `thumbnail_path` nor `thumbnail_url` is provided in `metadata.yaml`, the repository is searched for a `thumbnail.png` file, which if found is used for `thumbnail_path`. If `thumbnail_url` is provided, then `thumbnail_path` is ignored. Otherwise if `thumbnail_path` is provided or inferred, it's used to generate a `thumbnail_url`.

If a `thumbnail_url` exists, the output file `variables.json` will contain a `thumbnail_url` field that can be used for the `og:image` HTML property.

It is possible we could combine `thumbnail_url` and `thumbnail_path` into a single metadata field... like `thumbnail` and infer whether its a local path or URL. @vincerubinetti do you have a preference?

**Comment by dhimmel** [comment]
> It is possible we could combine `thumbnail_url` and `thumbnail_path` into a single metadata field... like `thumbnail` and infer whether its a local path or URL. 

After more thought, I think this is best.

Proposed implementation documented in https://github.com/manubot/rootstock/pull/277/commits/4db2e2f1293d12e2c8da9fe714e6de7b64b5f5f9

**Comment by dhimmel** [comment]
The recent updates seem to set the facebook thumbnail preview properly as per their [sharing debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgit.dhimmel.com%2Fbitcoin-whitepaper%2Fv%2F613f2bf50275f990caf2c1d8ec3d49c91654051c%2F). We do get a warning:

> The following required properties are missing: og:description, fb:app_id
