### ISSUE TITLE
Printing with Chrome on a Mac / default settings -> words run off page on US letter

### ISSUE THREAD

**Issue by cgreene** [manubot/rootstock#270]
Printing the PDF generated at https://greenelab.github.io/biopriors-review/v/7e8a3a2c7f58bf8fee3c1547870f54f98141fdb1/manuscript.pdf from Chrome on a mac  leads to text that runs off the page.

> ![Screen Shot 2019-10-09 at 2 12 15 PM](https://user-images.githubusercontent.com/542643/66508411-0f5d8e80-ea9f-11e9-9319-b430ffec21bb.png)

This isn't apparent before the print dialog in chrome:

> ![Screen Shot 2019-10-09 at 2 11 59 PM](https://user-images.githubusercontent.com/542643/66508424-184e6000-ea9f-11e9-8ca6-2af4e2ea1a57.png)

**Comment by dhimmel** [comment]
The PDF uses the paper size of "A4, Portrait (8.26 × 11.69 inch)". On a sheet of paper with this size, the margins will appear correctly. The issue is that our lab printer in the U.S. uses "letter" paper  (8.50 × 11.00 inch). [This page](http://betweenborders.com/wordsmithing/a4-vs-us-letter/) visualizes the size difference:

> ![image](https://user-images.githubusercontent.com/1117703/66510265-ae37ba00-eaa2-11e9-9727-fed66ce020f6.png)

If we switch to letter, then A4 paper will have the sides cutoff.

I can imagine a couple options:

1. Instruct users to print using "fit to size" scaling to reduce the dimensions of the text if needed.
2. Make sure our PDF margins accommodate paper with dimensions of 8.26 × 11.00 inch (the min in both dimensions).

***

We've previously struggled with this issue in https://github.com/manubot/rootstock/issues/105 and https://github.com/manubot/rootstock/pull/107. In https://github.com/manubot/rootstock/commit/a535f7b872df775b1557f90b01402bbd56d17517, we switched to letter size, but this is no longer part of the default CSS:

https://github.com/manubot/rootstock/blob/631b8a2d9efe8fc8c7b0fe8bf7d4cfe5239bcfb0/build/themes/default.html#L485-L489

So I guess athenapdf is defaulting to A4.

**Comment by vincerubinetti** [comment]
I think it makes more sense to specify a default size in whatever is actually doing the printing, rather than in the CSS which is usually harder to change. Thus I don't think we should hard code it into the CSS.

Two additional half measures we discussed in person:

1) Support better print configuration in the command line. When building a manuscript, it should say in the console something like `Building PDF with Athena PDF at paper size: A4`. This will make people more aware of what is going on and make errors easier to catch. We could also provide almost like a print dialog like any other to select the page size on every print: 
```
Current print size: A4
Change print size: 1) US Letter 2) A4 3) Other 4) Don't ask again (use current as default)
```

2) Always print two versions of the PDF: US Letter and A4, and include those words in the filename. This might make people more aware that there is a difference and that they'll have to do some kind of fitting/scaling.

---

> Instruct users to print using "fit to size" scaling to reduce the dimensions of the text if needed.

Where would we do this in a place that is obvious and useful but not distracting where it is irrelevant.

> Use a page size that is 8.26 × 11.00 inch (the min in both dimensions).

This might lead to hard to troubleshoot issues where users don't know why their margins aren't square. It's also sort of a dirty workaround, and not an actual solution.

I think the true solution is using my 1) above, and somehow making sure in print dialogs that "fit to page" is always selected.

**Comment by agitter** [comment]
Supporting print configuration through the command line, whether via an environment variable used by `build.sh` or something else, makes sense to me.

**Comment by dhimmel** [comment]
> Thus I don't think we should hard code it into the CSS.

I agree. The reason being is that now if someone prints the HTML from their browser, they can print to whatever page size their printer uses / the default for their locale. There is no issue currently when users print from HTML.

The issue occurs when users print `manuscript.pdf`. Currently the issue occurs for U.S.-based users whose paper is letter sized. The issue only occurs if the user does not select the "scale to fit" option in the print menu.

> Supporting print configuration through the command line, whether via an environment variable used by build.sh or something else, makes sense to me.

athenapdf [has](https://github.com/arachnys/athenapdf/issues/75) a `--pagesize` argument. We could add `--pagesize=A4` to `build.sh`, so manuscript creators see where to change it. For example, if you know most of your readers will be U.S. based, you might want to specify `--pagesize=Letter`.

But the main problem is that the person who is printing the PDF manuscript is rarely the one who is configuring `build.sh`.

**Comment by agitter** [comment]
> But the main problem is that the person who is printing the PDF manuscript is rarely the one who is configuring build.sh.

That is also true for authors who generate a PDF manuscript from LaTeX.  I don't see it as a big problem if the person who runs `build.sh` sets an athenapdf `--pagesize` that makes sense for their locale.  I like the idea of making that configurable in the build script.

**Comment by dhimmel** [comment]
>  I like the idea of making that configurable in the build script.

See https://github.com/manubot/rootstock/pull/272. I don't use an environment variable because at this point it's probably easier to change just the one line.

## General advice to readers

If you are printing a manuscript whose PDF uses a different page size than your physical paper, either:

1. select "scale to fit" in the print options
2. print the HTML manuscript directly, which will automatically conform to your paper size
