### ISSUE TITLE
Hypothesis improvements

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/rootstock#281]
It seems like we need a bunch of Hypothesis tweaks, and it'd be good to do them all at once. Here's some changes we can think about making:

- have a button to completely unload and hide Hypothesis until the user explicitly opts-in
- add button to disable highlights when printing (it's conceivable that someone would want to print with their Hypothesis highlights, so I think it should be an option)
- modify sidebar appearance to match with manubot default theme better

Combines and addresses: #111 #280

**Comment by vincerubinetti** [comment]
I've created an issue on the Hypothesis client here:
https://groups.google.com/a/list.hypothes.is/forum/#!searchin/dev/disable%7Csort:date/dev/x6Fbyey5MFw/1rJeFQDUAAAJ

Until they add this feature officially, it may be difficult/problematic to have a true on/off toggle button.

**Comment by dhimmel** [comment]
> Until they add this feature officially, it may be difficult/problematic to have a true on/off toggle button.

Would be great to full on/off toggle. If that is not an option, toggle-on alone would still improve the user experience. The idea would be as follows:

1. hypothesis off by default. this would make it harder for #306 to occur. It also would avoid the slow page loads on localhost due to spurious annotations. Ideally the UI element to activate hypothesis could show how many annotations existed... so users can avoid activating when there's nothing to see. I'll look into whether this is possible.

2. user activates hypothesis. Sidebar appears. If it's able to be deactivated... great. If not, a refresh would still remove it.

**Comment by dhimmel** [comment]
> Ideally the UI element to activate hypothesis could show how many annotations existed... so users can avoid activating when there's nothing to see. I'll look into whether this is possible.

Using the [api v1 search enpoint](https://h.readthedocs.io/en/latest/api-reference/v1/#tag/annotations/paths/~1search/get):

https://api.hypothes.is/api/search?limit=0&url=https://lelaboratoire.github.io/rethink-prs-ms/

```json
{"total": 122, "rows": []}
```

**Comment by vincerubinetti** [comment]
Hypothesis seems to have recently refreshed the look of their sidebar, and I think it looks better now, so I don't feel the need to rewrite their CSS right now.

**Comment by vincerubinetti** [comment]
> add button to disable highlights when printing (it's conceivable that someone would want to print with their Hypothesis highlights, so I think it should be an option)

Hypothesis already has a button for this built in, the eye button. Now that we'll have Hypothesis unloaded, so highlights will not show until user explicitly opts in. This is related to #280 which will also be closed by the linked PR.

**Comment by vincerubinetti** [comment]
Relevant for the future if we want to add an unload button:

https://groups.google.com/a/list.hypothes.is/forum/?utm_medium=email&utm_source=footer#!msg/dev/x6Fbyey5MFw/1rJeFQDUAAAJ
