### ISSUE TITLE
Figure tooltip includes whole manuscript

### ISSUE THREAD

**Issue by dhimmel** [manubot/rootstock#284]
Hover over "Figure 1" at https://gweissman.github.io/icu_ml_ms/v/59d6bae8e44136e33978320d069ad7f8aa0cf22f/ and see:

> ![Screen Shot 2019-12-12 at 2 59 11 PM](https://user-images.githubusercontent.com/1117703/70745782-983cb480-1cf2-11ea-8016-9d7ef30f8c63.jpeg)

The figure tooltip includes more than the figure. It seems to include the whole manuscript.

This is also happening on the latest rootstock. See https://manubot.github.io/rootstock/v/cf9e16be57ff95fba6b98a4dc064faece8cd41a8/

My guess is that we updated something that broke how the figure tooltip plugin works. CC @vincerubinetti 

Thanks @trang1618 for reporting this.

**Comment by vincerubinetti** [comment]
I believe this is because `fignos` changed. The element that the figure `id` is attached to has changed.

Here is what it was, and here is what it still is on my local (up to date) version of Manubot and rootstock:
![image](https://user-images.githubusercontent.com/8326331/70750106-b9ee6980-1cfb-11ea-9ded-eadaf5605522.png)

Here is what it is now:
![image](https://user-images.githubusercontent.com/8326331/70750045-99261400-1cfb-11ea-91a5-f3c2b618f1a1.png)

**Comment by vincerubinetti** [comment]
Here is the code responsible:
https://github.com/manubot/rootstock/blob/master/build/plugins/tooltips.html#L407-L415

If it's a figure id, the target gets modified to be the parent of the target, because previously we had to jump from the `<img>` with the id to its parent `<figure>` container, so we could also get the caption. Now that the id has moved to a `<div>` that is a first generation child of `<body>`, the whole body of the document gets put into the tooltip.

We can simply take out line 410 and 411, and that should fix the issue. Or we can add checks throughout these plugins (because several others do operations like this) to try to make sure we're never referring to the `<body>`.

**Comment by vincerubinetti** [comment]
PS. You'll note that the `jump-to-first` plugin also stopped working, for the same reason. And it seems that `tablenos` was updated too, so similar errors might occur for tables.

**Comment by dhimmel** [comment]
Must have been https://github.com/manubot/rootstock/commit/a121e479506eb0232a418bb2ac5b05ebe291ab34 which updated the environment and included major version increments for `pandoc-eqnos`, `pandoc-fignos`, `pandoc-tablenos`, and `pandoc-xnos`. Note to self to double check all functionality still works after major version upgrades.

From the [fignos readme](https://github.com/tomduck/pandoc-fignos/blob/master/README.md#whats-new) about the 2.0 release

> The figure is now enclosed in a `<div>` which contains the `id` and class `fignos`.  This change was made to facilitate styling.  The `id` was formerly contained in an anchor tag.

From [eqnos readme](https://github.com/tomduck/pandoc-eqnos/blob/master/README.md#whats-new):

> The equation is now enclosed in a `<div>` which contains the `id` and class `eqnos`. This change was made to facilitate styling, and for consistency with pandoc-fignos and pandoc-tablenos. An inline-block `<span>` was formerly used instead.

From [tablenos readme](https://github.com/tomduck/pandoc-tablenos/blob/master/README.md#whats-new):

> The table is now enclosed in a `<div>` which contains the `id` and class `tablenos`. This change was made to facilitate styling. The `id` was formerly contained in an anchor tag.

**Comment by dhimmel** [comment]
@vincerubinetti how much modification to the plugins is needed to support the new `*nos` syntax? I think we can probably drop support for the old syntax, since users should update their environments.

**Comment by vincerubinetti** [comment]
Not much effort. It's just a brittle solution, which is why i opened #285 . But if you can help me make sure i have the latest `*nos` plugins on my local machine so I can test the fix PR, I can do it very quick.

**Comment by dhimmel** [comment]
> make sure i have the latest *nos plugins on my local machine

With the latest code checkout out, from the rootstock root directory, run:

```
conda env update --file ci/environment.yml
```
