### ISSUE TITLE
References not working

### ISSUE THREAD

**Issue by Nebucatnetzer** [manubot/rootstock#295]
I have two references which I just can't get to work:

```
erheblich gesenkt werden. Somit hat die neue Ist-Situation, Abbildung:({@fig:risknew}),
eine bessere Risikobewertung als das geplante Soll-Risiko, Abbildung:({@fig:riskgrey}).

![Risikoanalyse der Soll-Situation in grau](images/sollrisiko_grey.svg){#fig:riskgrey width="7.2cm"}
![Risikoanalyse der neuen Ist-Situation](images/ist_risiko_neu.svg){#fig:risknew width="7.2cm"}
```

I tried with and without {}, with and without dash. I copy pasted the name just to be sure.
I don't have any idea left what I could try.

**Comment by dhimmel** [comment]
Syntax looks good to me.

What if you put a space like `Abbildung: (@fig:riskgrey)`.

If that doesn't work, let us know and I'll investigate meet time I'm at a full computer (could be a few days).

**Comment by Nebucatnetzer** [comment]
That didn't work either, all the other references work fine (ca. 29 tables and 32 figures) and the pictures itself work as well. If you have time to have a look that would be great and it's just for testing so there's no deadline for me :).
The code can be found here:
https://github.com/Nebucatnetzer/manubot_test

**Comment by dhimmel** [comment]
Looking at the [output here](https://nebucatnetzer.github.io/manubot_test/v/d37d89c2e56c65b15b9c2925cf293a69d5d5c873/#zielbewertung):

> ![image](https://user-images.githubusercontent.com/1117703/71483285-1742ea00-27d5-11ea-876d-0ccb28ac5c13.png)

I see that the figures don't have their captions displayed. I think this is because there is no newline between the figures. So try changing to:

```
![Risikoanalyse der Soll-Situation in grau](images/sollrisiko_grey.svg){#fig:riskgrey width="7.2cm"}

![Risikoanalyse der neuen Ist-Situation](images/ist_risiko_neu.svg){#fig:risknew width="7.2cm"}
```

Then pandoc will create HTML `<figure>` elements rather than just `<img>` elements. The two figures will no longer be side-by-side. If you want them side by side, the easiest way would be to combine them into a single SVG.

There is also a concept called subfigures in the `pandoc-crossref` filter that does this, but we don't use this filter and applying it will probably take considerable work and debugging.

**Comment by Nebucatnetzer** [comment]
That solved it thank you. For the moment I'm happy with the working reference. I'll check at a later point if I would like to have the images side by side.
