### ISSUE TITLE
using external editor

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#332]
I am new to Manubot/github and working on converting my first manuscript to Manubot. 
I would like to use the Atom editor to edit the markdown code for the manuscript. That edits the copy of the file on my computer. How do I turn that into a pull request? Is there a way to push the text from my computer to the GitHub repository?

**Comment by dhimmel** [comment]
> I would like to use the Atom editor to edit the markdown code for the manuscript.

Okay. That is certainly possible! Git is the program that tracks changes to your local files and allows uploading ("pushing") the changes the GitHub. Once the changes are pushed to GitHub, they will show up in your online manuscript.

Atom has [git/GitHub integration](https://github.atom.io/), so you will be able to do git operations from your text editor without having to type commands. However, understanding how to use Git, even from the text editor, has a steep learning curve. Manubot assumes users have a basic understanding of Git. If that's not the case, it's probably not the right tool for you.

Now if you'd like to learn Git, and do so through using Manubot, that's great. But otherwise it might be a bit frustrating.

The steps you need to do:

1. edit your text file.
2. add (also called stage) the files with the edits
3. create a commit to make a snapshot with the changes
4. push the changes to GitHub

**Comment by agitter** [comment]
@thorowitz are you interested in using Manubot to write your own manuscript (in a GitHub repository you created) or contribute to an existing one?  It would be easier to write to your own GitHub repository in Atom than to contribute to an existing manuscript.  However, it requires some technical steps to set up your own manuscript repository.

To contribute to someone else's manuscript, you would need to create your own fork of their repository.  For example, you created the fork https://github.com/thorowitz/try-manubot of the repository https://github.com/manubot/try-manubot.

When I tested Atom, it asks me to select which "remote" (version of the repository on GitHub) I want to use:
![image](https://user-images.githubusercontent.com/3532898/79798116-1f8fd980-831e-11ea-9d9d-ff84ff0b1ff5.png)

Picking a single remote makes later steps tricky.  Typically, you would make changes on your local machine, push the changes to your fork of the manuscript on GitHub (https://github.com/thorowitz/try-manubot), and then make a pull request on the original GitHub repository (https://github.com/manubot/try-manubot) to integrate your changes with the main version of the manuscript.  After your proposed changes were accepted, you would pull from the original repository so that your next round of changes use the current document in case others have also made changes.

This is discussed in Atom's forum [here](https://discuss.atom.io/t/set-github-pull-to-different-url/49279), but I didn't see clear advice.

Many new git and GitHub users start off by using the GitHub interface to make edits and pull requests to Manubot manuscripts.  It is somewhat less convenient than writing in a local editor but much easier to execute.  This 2 min [video](https://manubot.org/docs/getting-started.html) shows that process.

**Comment by thorowitz** [comment]
@dhimmel: Thanks, I figured out how to get Atom to stage changes and generate a pull request. It's working pretty smoothly now.
@agitter: I'm writing a manuscript where I have done the first draft, but I expect a lot of people to each make small contributions to.

**Comment by thorowitz** [comment]
Thanks for your help!
