### ISSUE TITLE
Tables in docx build don't come out right

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#344]
The tables in my document look good in pdf but come out looking crappy in the docx file

Here is the Markdown for an example:

```markdown
| Barriers that Hinder Collaborations Between Researchers and Clinicians.|
|:------------------|
|1. Time Pressures for Clinicians.<br> - Access to clinicians is limited in terms of collaborations and participation in reader studies.<br> - Research platforms such as “pop-up” labs at national meetings should be fostered.<br> - Incentives (i.e., CEM/RME Credit) should be provided to clinicians. |
| 2. Lack of Networking Among Disciplines.<br> - Increase the probability of serendipitous collaborations by creating a "matchmaking" resource.|
| 3. Limited Access to and Utility of Image Datasets.<br> – Foster annotation projects to make datasets more useful to researchers|
```
In the pdf, it's a pretty table, with shading and borders and all the subpoenas lined up properly.

In docx, it looks like this:

Barriers that Hinder Collaborations Between Researchers and Clinicians.
--
1. Time Pressures for Clinicians. - Access to clinicians is limited in terms of collaborations and participation in reader studies. - Incentives (i.e., CEM/RME Credit) should be provided to clinicians.
2. Lack of Networking Among Disciplines. - Increase the probability of serendipitous collaborations by creating a “matchmaking” resource.
3. Limited Access to Image Datasets

Is there something I can do to improve the docx output? Maybe in the "default.docx" document?

**Comment by dhimmel** [comment]
> In docx, it looks like this:

Any chance you could add a screenshot or the DOCX file?

**Comment by thorowitz** [comment]
Here's the docx
<img width="652" alt="docx table" src="https://user-images.githubusercontent.com/63421291/83636503-137d7580-a574-11ea-8d6c-fab93f311cb1.png">

and here's the pdf, for reference
<img width="912" alt="pdf table" src="https://user-images.githubusercontent.com/63421291/83636542-209a6480-a574-11ea-8190-c0bf49de1a02.png">

**Comment by dhimmel** [comment]
Ah, so the issue is that default DOCX style has invisible gridlines. I agree it'd be much better to see the grid-lines, and perhaps even have alternate row shading (if that's possible). I believe you can edit the DOCX style by changing [`build/themes/default.docx`](https://github.com/manubot/rootstock/blob/b7462701ff85854a67d878db4af89d0268bb11d2/build/themes/default.docx), which gets passed to pandoc:

https://github.com/manubot/rootstock/blob/b7462701ff85854a67d878db4af89d0268bb11d2/build/pandoc/defaults/docx.yaml#L5

See https://pandoc.org/MANUAL.html#option--reference-doc:

> Use the specified file as a style reference in producing a docx or ODT file.
For best results, the reference docx should be a modified version of a docx file produced using pandoc. The contents of the reference docx are ignored, but its stylesheets and document properties (including margins, page size, header, and footer) are used in the new docx.

@thorowitz see if you're able to edit or create a better `--reference-doc` DOCX file that improves table formatting. I think we'd be interested in updating the rootstock version, if anyone is able to improve it.

As a side note, it seems odd to use a table for your application. Instead it seems like it should be a list like:

***

Barriers that Hinder Collaborations Between Researchers and Clinicians.

1. Time Pressures for Clinicians.
   - Access to clinicians is limited in terms of collaborations and participation in reader studies.
   - Incentives (i.e., CEM/RME Credit) should be provided to clinicians.
2. Lack of Networking Among Disciplines.
    - Increase the probability of serendipitous collaborations by creating a “matchmaking” resource.
    - Limited Access to Image Datasets

**Comment by thorowitz** [comment]
@dhimmel : I agree it's an odd use for the table format. But that's what we're going with for the moment.
I will try my hand at editing the reference doc.
However, the other problem is that the subpoints `<br> - `are not coming out indented on separate lines, as in the pdf version, but as all one line, with dashes.

**Comment by dhimmel** [comment]
> However, the other problem is that the subpoints `<br> - `are not coming out indented on separate lines, as in the pdf version, but as all one line, with dashes.

From https://pandoc.org/MANUAL.html#backslash-escapes

> A backslash-escaped newline (i.e. a backslash occurring at the end of a line) is parsed as a hard line break. It will appear in TeX output as `\\` and in HTML as `<br />`. This is a nice alternative to Markdown's "invisible" way of indicating hard line breaks using two trailing spaces on a line.

Try ending the line with `\` or `  ` (two-spaces) in the markdown.
