### ISSUE TITLE
is docker required for local PDF builds?

### ISSUE THREAD

**Issue by ctb** [manubot/rootstock#368]
I tried doing local builds, per https://github.com/manubot/rootstock#local-execution, and got the following error:

```
Exporting HTML manuscript
[INFO] Running filter pandoc-fignos
[INFO] Completed filter pandoc-fignos in 18 ms
[INFO] Running filter pandoc-eqnos
[INFO] Completed filter pandoc-eqnos in 10 ms
[INFO] Running filter pandoc-tablenos
[INFO] Completed filter pandoc-tablenos in 9 ms
[INFO] Running filter pandoc-manubot-cite
[INFO] Completed filter pandoc-manubot-cite in 11 ms
[INFO] Running filter pandoc-citeproc
[INFO] Completed filter pandoc-citeproc in 18 ms
Exporting PDF manuscript using Docker + Athena
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

so, seems like it - but not mentioned anywhere in documentation. ??

**Comment by dhimmel** [comment]
Currently, we check whether the docker command exists on the system. If so we use it to produce the PDF. 

https://github.com/manubot/rootstock/blob/15db6237effc6edb2b8e675ea5cb8a17188d1e2c/build/build.sh#L38-L39

https://github.com/manubot/rootstock/blob/15db6237effc6edb2b8e675ea5cb8a17188d1e2c/build/build.sh#L55-L57

When the docker command doesn't exist, we use WeasyPrint, which should be part of the conda environment:

https://github.com/manubot/rootstock/blob/15db6237effc6edb2b8e675ea5cb8a17188d1e2c/build/build.sh#L41-L44

Note that in the future we might remove WeasyPrint, but it works for now.

So the issue seems to be that your system has docker installed but not running. We should consider updating the build script to check whether docker is running.

Let me prototype a command for this.

**Comment by ctb** [comment]
ah-hah! got it. thanks!

(yes, indeed, I do not keep docker running most of the time.)

**Comment by dhimmel** [comment]
We could replace line 39 above with:

```bash
DOCKER_EXISTS="$(docker info >/dev/null 2>&1 || true)" 
```

You can also do this now for a local fix.

Another option is to launch Docker on macOS like https://stackoverflow.com/a/48843074/4651668, but I think I lean against it, since launching a heavy application like Docker should probably be opt-in from the user's perspective.

**Comment by ctb** [comment]
(this is not a high priority by any means!)

I will test that in the script next time I'm working with manubot. Thanks for the quick response!

Agree re no launch.

**Comment by ctb** [comment]
works for me, thanks!
