### ISSUE TITLE
Citation not resolved

### ISSUE THREAD

**Issue by habi** [manubot/rootstock#379]
I cannot figure out how to cite two publications in my manuscript: https://github.com/habi/zmk-tooth-cohort-method-manuscript/issues/3

At first I thought it's because the one has brackets in it, but neither escaping these nor using the ShortDOI helps `manubot` to resolve it.
A second one is also not working, as specified in the issue above.

Is there a way I can debug this, e.g. a log file I could try to read?

**Comment by agitter** [comment]
For the short DOI, Manubot expects a prefix `10/` before the shortened part.  Specifically, using `doi:10/c9wr8n` for this reference should work.  In Manubot locally I get:
```
$ manubot cite --render doi:10/c9wr8n
1. Root canal anatomy of the human permanent teeth
Frank J. Vertucci
Oral Surgery, Oral Medicine, Oral Pathology (1984-11) https://doi.org/c9wr8n
DOI: 10.1016/0030-4220(84)90085-9
```

The error with `doi:10.3233/978-1-61499-649-1-87` is trickier.  There is a problem with the DataCite record for this DOI: https://data.crosscite.org/10.3233/978-1-61499-649-1-87

Unfortunately, you may need to create a [manual reference](https://github.com/manubot/rootstock/blob/master/USAGE.md#reference-metadata) to get this one formatted correctly.  Sometimes citing by URL instead of DOI works, but that fails for this particular manuscript:.  Citing `https://eprints.soton.ac.uk/403913/` is close but the DOI field is wrong.
```
$ manubot cite --render http://doi.org/10.3233/978-1-61499-649-1-87
1. IOS Press Ebooks - Jupyter Notebooks – a publishing format for reproducible computational workflows http://ebooks.iospress.nl/publication/42900

$ manubot cite --render https://eprints.soton.ac.uk/403913/
1. Jupyter Notebooks – a publishing format for reproducible computational workflows
Thomas Kluyver, Benjamin Ragan-Kelley, Fernando Pérez, Brian Granger, Matthias Bussonnier, Jonathan Frederic, Kyle Kelley, Jessica Hamrick, Jason Grout, Sylvain Corlay, … Jupyter development team
Positioning and Power in Academic Publishing: Players, Agents and Agendas (2016) https://eprints.soton.ac.uk/403913/
DOI: kluyver, thomas, ragan-kelley, benjamin, pérez, fernando, granger, brian, bussonnier, matthias, frederic, jonathan, kelley, kyle, hamrick, jessica, grout, jason, corlay, sylvain, ivanov, paul, avila, damián, abdalla, safia, willing, carol and jupyter development team, (2016) jupyter notebooks – a publishing format for reproducible computational workflows. loizides, fernando and scmidt, birgit (eds.) in positioning and power in academic publishing: players, agents and agendas. ios press. pp. 87-90 . (doi:10.3233/978-1-61499-649-1-87 http://dx.doi.org/10.3233/978-1-61499-649-1-87).
```

Let us know if you'd like help with the manual reference.

Regarding debugging citation errors, you can access the build logs.  Start with the "Manubot passing" button at https://github.com/habi/zmk-tooth-cohort-method-manuscript.  Then click the name of the last commit.  Then click the lower "Manubot" on the sidebar to the left.  You'll open the GitHub Actions build log.  You can expand the step "Build Manuscript" to see error messages about citations or other content issues.

**Comment by habi** [comment]
> For the short DOI, Manubot expects a prefix `10/` before the shortened part.

Thanks, I haven't seen that in https://github.com/manubot/rootstock/blob/master/USAGE.md :)

**Comment by habi** [comment]
> Citing `https://eprints.soton.ac.uk/403913/` is close but the DOI field is wrong.

Citing Jupyter is anyways an issue: https://github.com/jupyter/jupyter/issues/190, but citing it with the URL doesn't work either: https://github.com/habi/zmk-tooth-cohort-method-manuscript/commit/6938ff5fe14fcb7c2f523a165f1238bc94347f61
I'll look into the log in Monday and try to figure out how to render it correctly.

Thanks a lot for the speedy help/input!

**Comment by dhimmel** [comment]
To fix the bad jupyter reference, you can take the CSL JSON from:

https://github.com/habi/zmk-tooth-cohort-method-manuscript/blob/443a37d93db98cac5d9806516087a4f7e53e9176/references.json#L882-L984

You can then edit the bad fields like DOI and save the fixed CSL JSON in `content/manual-references.json`.

**Comment by dhimmel** [comment]
> Is there a way I can debug this, e.g. a log file I could try to read?

One more comment on the CI build logs. If you look at the build for your most recent commit, you can see [there is a warning](https://github.com/habi/zmk-tooth-cohort-method-manuscript/runs/1299829740#step:7:44) about another misformated citation:

```
Inspection of dealiased citekeys revealed potential problems:
doi:/10.1016/j.joen.2019.11.006 -- DOIs must start with '10.' (or '10/' for shortDOIs).
```

**Comment by dhimmel** [comment]
closing this since https://github.com/habi/zmk-tooth-cohort-method-manuscript/issues/3 is now closed. Any suggestions still welcome.

**Comment by habi** [comment]
Closing is fine, I'll have to keep the information on how to fix the bad Jupyter reference, though.
It's in the submitted version of the manuscript, but it's still malformed :)
