### ISSUE TITLE
The `add-path` command is deprecated and will be disabled on Nov 16

### ISSUE THREAD

**Issue by fmsabatini** [manubot/rootstock#388]
When building my Manubot manuscript, I'm getting a series of warnings related to 
the fact that the commands `add-path` and `set-env` are going to be deprecated soon

https://github.com/fmsabatini/sPlotOpen_Manuscript/actions/runs/354512839

Is is something related to my manuscript, or something that should be taken care at the manubot level?
In the first case, what should I change to avoid problems next week?
Thanks

**Comment by dhimmel** [comment]
see https://github.com/manubot/rootstock/pull/385#discussion_r518807980 and https://github.com/conda-incubator/setup-miniconda/issues/84. https://github.com/conda-incubator/setup-miniconda/releases/tag/v2.0.0 was just released, so let me upgrade the rootstock CI.

Best that I do this ASAP since everyone will be upgrading to the latest rootstock as a result of #387 .

**Comment by dhimmel** [comment]
I had seen this warning before, but this is the first time I saw the date:

> The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Eek! That's soon.

It's possible conda-incubator/setup-miniconda will update `@v1` with the fix. Otherwise, old manuscripts might fail. But I guess in this case that's less of a problem than usual (:
