### ISSUE TITLE
Create a init script? 

### ISSUE THREAD

**Issue by swamidass** [manubot/rootstock#401]
The instructions for starting a new manuscript are pretty involved: https://github.com/manubot/rootstock/blob/master/SETUP.md

Could you add a set up script which would make this work differently? E.g. make it so that manubot can be "installed," such that it provides a command line tool, which can create a new manuscript. This would reduce the process to a single command, and also make it the process maintainable.

**Comment by agitter** [comment]
Initially we did not attempt to automate more of the setup steps because there were two steps that were typically performed outside the command line: creating the new repository on GitHub and setting up continuous integration.  Now that the default continuous integration moved to GitHub Actions, creating the repository is probably the only step that would need to be automated in order to create a new manuscript with a single script.

An intermediate step would be to reorder the instructions.  The user could first create the new repository at https://github.com/new.  Then, they could run a script to convert that new, empty repository into a Manubot manuscript.

Automating everything would require authenticating at the command line.  The GitHub API can be used to [create a repository](https://docs.github.com/en/free-pro-team@latest/rest/guides/getting-started-with-the-rest-api#create-a-repository).  It looks like it requires a token, which could be less user-friendly than our current setup process.  The GitHub command line interface has a [create command](https://cli.github.com/manual/gh_repo_create) and supports more [authentication options](https://cli.github.com/manual/gh_auth_login).  However, that would add an additional dependency to the setup.
