### ISSUE TITLE
figure and table numbering error

### ISSUE THREAD

**Issue by thorowitz** [manubot/rootstock#402]
In the latest build of my manuscript, the figure and table numbering is not working, such that both figures are figure 1 and both tables are table 1.

**Comment by agitter** [comment]
This may be related to problems from your last rootstock update.  The versions in `build/environment.yml` don't match the latest package versions from rootstock, in particular, `pandoc-fignos` and related numbering packages.

Let's try updating `build/environment.yml` to see if that fixes it.  The error you describe was a bug that was fixed in `pandoc-fignos` version 2.3.0 https://github.com/tomduck/pandoc-fignos/issues/76

**Comment by thorowitz** [comment]
Seems to be working now. Thanks!
