### ISSUE TITLE
Images not rendering in the html or pdf version of the manuscript

### ISSUE THREAD

**Issue by jaybee84** [manubot/rootstock#410]
Is there a maximum image size that is recommended for figures so that they render successfully in the pdf or html version of the manuscript?

**Comment by dhimmel** [comment]
> Images not rendering in the html or pdf version of the manuscript

I don't think this would be caused by images that are too large (in terms of file size or dimensions).

Is the manuscript where you're having problems available? If so, I could take a look to see what might be going wrong.

> Is there a maximum image size that is recommended for figures

For raster images, I'll often do a resolution of 300 dpi. This is higher resolution than required for unzoomed viewing, but is useful for crisp graphics and users who want to zoom in. Anything higher might be adding to the file size without much benefit.

**Comment by jaybee84** [comment]
Thanks @dhimmel ..

The manuscript with the rendering issues is here: https://jaybee84.github.io/ml-in-rd/
Repo: https://github.com/jaybee84/ml-in-rd

We have been using 300dpi resolution, but are still running into rendering issues

**Comment by agitter** [comment]
I'm guessing that the problem is due to the file type instead of the file size.  When we use .svg or .png images, they are included in the HTML version of the manuscript using the `img` tag.  These .pdf images are being included in the HTML manuscript with the `embed` tag:
https://github.com/jaybee84/ml-in-rd/blob/d50246a066419e86967240c4f933f0cc3047c74e/manuscript.html#L179

I'm not sure whether it is possible to use .pdf images or whether they'll need to be converted to .svg first.

**Comment by jaybee84** [comment]
We have also tried with .png and .tiff versions but got the same result.

**Comment by agitter** [comment]
Can you please point me to a commit in the commit history where you were using .png images?  That may give me more ideas for debugging this.

**Comment by jaybee84** [comment]
Commits using full size tiff/png files : https://github.com/jaybee84/ml-in-rd/pull/145/commits
Commits using reduced size png files: https://github.com/jaybee84/ml-in-rd/pull/167/commits

**Comment by agitter** [comment]
https://github.com/jaybee84/ml-in-rd/pull/145 should work if you modify the relative file path to the image file.  Instead of 
`ml-in-rd/content/images/figures/pdfs/dimensionality-reduction.png`
it has to be relative to `content` so
`images/figures/pdfs/dimensionality-reduction.png`

https://github.com/jaybee84/ml-in-rd/pull/167 added png versions of the images.  However, to use those you will also need to switch to those versions of the files in the text where the image is displayed.

**Comment by jaybee84** [comment]
Thanks @agitter! changing the path of the image file helped! 
Also, added the right versions in jaybee84/ml-in-rd#167  and that helped as well!

**Comment by agitter** [comment]
Great!  I'm glad that worked.

I'm still a little confused about what degree of PDF image support Pandoc has, but we can save that question for another day.
