### ISSUE TITLE
Add `gh repo create` to SETUP.md

### ISSUE THREAD

**Issue by lubianat** [manubot/rootstock#418]
Something like: 
"
If you have GitHub for command line configured, you can run:
`$ gh repo create` 
and proceed with the setup. Otherwise, you'll have to manually create an empty GitHub repository at <https://github.com/new>.
Make sure to use the same "Owner" and "Repository name" specified above.
Do not initialize the repository, other than optionally adding a Description.
Next, push your cloned manuscript:
"

If it makes sense to you, I'd gladly make a (better) pull request.

**Comment by dhimmel** [comment]
Great suggestion @lubianat. For those who aren't aware, `gh` is the GitHub command line tool ([source](https://github.com/cli/cli), [manual](https://cli.github.com/manual/)). Presence of this utility would greatly help automate the Manubot setup process, however only a small portion of users likely have this installed.

There's currently a PR in progress at https://github.com/manubot/rootstock/pull/417 that adds a manubot setup script. This would be an espectially valuable addition in the context of this script, because it would remove the sole remaining manual step. CC @nfry321.

But I don't want to complicate an already large PR, so I suggest we proceed with #417 without `gh repo create` support. But we can consider whether it could be added to the setup script after #417.

As far as editing the existing manual setup docs, @lubianat I think you could make a PR now.
