### ISSUE TITLE
citation error

### ISSUE THREAD

**Issue by jxchen01** [manubot/rootstock#472]
I got the following error message when compiling some manual reference items:

```
## ERROR
Generating csl_item for 'HDN' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'HDN'
## ERROR
Generating csl_item for 'attentionUnet' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'attentionUnet'
```

My `manual-references.json` is as follows:
```
[
    {
    "id": "attentionUnet",
    "type": "paper-conference",
    "title": "Attention U-Net: Learning Where to Look for the Pancreas",
    "container-title": "Proceedings of Medical Imaging with Deep Learning 2018",
    "URL": "https://openreview.net/forum?id=Skft7cijM",
    "author": [
      {
        "family": "Oktay",
        "given": "Ozan"
      },
      {
        "family": "Schlemper",
        "given": "Jo"
      },
      {
        "family": "Le Folgoc",
        "given": "Loic"
      },
      {
        "family": "Lee",
        "given": "Matthew"
      },
      {
        "family": "Heinrich",
        "given": "Matthias"
      },
      {
        "family": "Misawa",
        "given": "Kazunari"
      },
      {
        "family": "Mori",
        "given": "Kensaku"
      },
      {
        "family": "McDonagh",
        "given": "Steven"
      },
      {
        "family": "Hammerla",
        "given": "Nils Y."
      },
      {
        "family": "Kainz",
        "given": "Bernhard"
      },
      {
        "family": "Glocker",
        "given": "Ben"
      },
      {
        "family": "Rueckert",
        "given": "Daniel"
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2022",
          6,
          24
        ]
      ]
    }
  },
  {
    "id": "HDN",
    "type": "paper-conference",
    "title": "Interpretable Unsupervised Diversity Denoising and Artefact Removal",
    "container-title": "Proceedings of the Tenth International Conference on Learning Representations",
    "URL": "https://proceedings.mlr.press/v143/lalit21a.html",
    "author": [
      {
        "family": "Prakash",
        "given": "Mangal"
      },
      {
        "family": "Delbracio",
        "given": "Mauricio"
      },
      {
        "family": "Milanfar",
        "given": "Peyman"
      },
      {
        "family": "Jug",
        "given": "Florian"
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2022",
          6,
          26
        ]
      ]
    }

]
```

The error message doesn't contain any information about what is not implemented. Any idea of what could be wrong?

Many thanks!

**Comment by dhimmel** [comment]
Hmm, that is odd. If you provide manubot with a citation like `[@attentionUnet, @HDN]` it will fail because those are not recognized persistent identifiers. However, you appear to providing the reference metadata in `manual-references.json`, such that there shouldn't be a problem.

Are you using a recent version of manubot/rootstock? Could there be reason `manual-references.json` is not getting used as a bibliography? Not sure if the repo is public, if so I can also look directly (or if you temporarily add me as a repo collaborator)

**Comment by agitter** [comment]
I've gotten errors like that when my `manual-references.json` can't be parsed properly so none of the of the ids defined within are recognized.  Have you tried running it through a linter like http://www.yamllint.com/?  I think it may be missing a `}` at the very end of the second reference.

**Comment by jxchen01** [comment]
Dear @dhimmel , I just added you to repo (still private, but will be public soon). This is the first time our group writes together with manubot. Very refreshing experience. I would really appreciate if you can take a quick look and advice on any potential issues with my manual reference file.

**Comment by jxchen01** [comment]
> I've gotten errors like that when my `manual-references.json` can't be parsed properly so none of the of the ids defined within are recognized. Have you tried running it through a linter like http://www.yamllint.com/? I think it may be missing a `}` at the very end of the second reference.

Thanks for the suggestion! @agitter it looks like yamllint.com thinks my file is valid. The missing `}` in the message above was a mistake in my copy-and-paste.

**Comment by dhimmel** [comment]
Looking at the most recent build log under the Build Manuscript section, I see following on line 51:

```
## ERROR
load_bibliography: error reading 'content/manual-references.json'.
Expecting property name enclosed in double quotes: line 173 column 5 (char 3588)
```

Looks like the text `Roth,  Xu` might have accidentally got inserted on line 173 of `manual-references.json`. Perhaps your text editor has a JSON linter (or you could use a website) that could detect errors on the entire file.

One unrelated tip for DOI citations. Do `@doi:10.1371/journal.pcbi.1007128` or `@10.1371/journal.pcbi.1007128` rather than `@doi:https://doi.org/10.1371/journal.pcbi.1007128`.
